{
    "engines": {"lucee": {"docs": "https://docs.lucee.org/reference/functions/catch.html"}},
    "name": "catch",
    "description": "Used only inside a cftry, the cfcatch tag catches and process exceptions.",
    "syntax": "<catch/>",
    "returns": "void",
    "type": "tag",
    "params": [
        {
            "name": "name",
            "description": "The name for the struct containing the exception information\n\nby default it is cfcatch (in Lucee, the cfcatch variable will also be populated)",
            "default": false,
            "type": "string",
            "required": false
        },
        {
            "name": "type",
            "description": "Type of catch, default:Any",
            "default": false,
            "type": "string",
            "required": false
        }
    ]
}